---

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items:
    - { src: 'sshd_config', dest: "/etc/ssh/sshd_config", owner: 'root', group: 'root', mode: '0644' }

- name: Restart service ssh
  systemd:
    name: ssh
    state: restarted
